README.md, ecs_deploy.gemspec
I made some fixes to make documents more readable.
=> Trivial fixes in documentation

.gitignore, exe/ecs_auto_scaler, lib/ecs_deploy/auto_scaler.rb, lib/ecs_deploy/configuration.rb, lib/ecs_deploy/ecs_handler.rb, samples/config.yml
割と雜な感じですが、ECSとEC2を同時にAuto Scaleする機能を実装しました。
@tomykaira @threetreeslight レビューお願いします。
=> Imple AutoScaler

lib/ecs_deploy/capistrano.rb
特定のcluster、特定のtask_definitionに対してだけデプロイできるようにする機能を追加します。
意図としては、検証用のclusterだけデプロイしたり、特定のサービスコンポーネントだけ先行でデプロイして状況を確認するための機能です。
=> Add target_cluster, target_task_definition contraint

lib/ecs_deploy/auto_scaler.rb
polling感覚を短かくするため、idle_timeというconfigパラメーターを設けて、一度スケールしたらその時間を経過するまではpollingしない設定をできるようにします。
=> Add idle_time config

lib/ecs_deploy/auto_scaler.rb
APIサーバーの日中のミニマムを高めにして、夜間のミニマムを少なくする、等といった要求に応えられるように、scheduled_min_task_countという設定項目を追加します。
時間の期間とその期間でのミニマムのタスク数を指定します。
```
scheduled_min_task_count:
- {from: "10:00", to: "18:00", count: 5}
時間は、Time.parseによる雜な指定です。
`"10:00 +0000"`等と書けばタイムゾーンも指定できますが気を付けた方が良いかも。
=> Add scheduled_min_task_count

lib/ecs_deploy/service.rb
If user doesn't give desired_count, ECS keep current desired_count.
If Service is not created yet and desired_count is nil, desired_count is initialized by 0
@tomykaira @threetreeslight @taiSon
=> Enable not to give desired_count parameter to update_service API

lib/ecs_deploy/capistrano.rb
bug is following:
If some services has same task definition family,
this gem cannot find rollback target arn.
=> Fix rollback bug

ecs_deploy.gemspec, lib/ecs_deploy/capistrano.rb, lib/ecs_deploy/task_definition.rb
AWS announced the  IAM Roles for Tasks. 
https://aws.amazon.com/about-aws/whats-new/2016/07/amazon-ec2-container-service-now-supports-iam-roles-for-tasks/
This pull request makes work with it.
=> add support IAM Roles for Tasks.

lib/ecs_deploy/auto_scaler.rb
Make decrease process safer.
1. deregister container instance that is not running any tasks.
1. detatch deregistered instance from auto scaling group.
1. terminate detatched instance.
=> Safer decrease process

lib/ecs_deploy/service.rb
When an ECS cluster has more than 10 ecs services, then `client.wait_until` failed.
```
cap aborted! 
Aws::Waiters::Errors::UnexpectedError: stopped waiting due to an unexpected error: service names can have at most 10 items. 
... (stack trace)
The deploy has failed with an error: stopped waiting due to an unexpected error: service names can have at most 10 items. 
```
=> Fix wait service stable

lib/ecs_deploy/service.rb
I mistake `each_slice` for `each_cons` ...
=> Fix waiting for service stable

README.md, lib/ecs_deploy/capistrano.rb, lib/ecs_deploy/task_definition.rb
I recommend to use other execution way. (ex. https://github.com/reproio/wrapbox)
=> Remove execution feature

ecs_deploy.gemspec, lib/ecs_deploy/capistrano.rb, lib/ecs_deploy/service.rb, lib/ecs_deploy/task_definition.rb
Support new features. (main purpose is Fargate support)
- Support placement_constraints and strategies
- Support Task level CPU, Memory constraints
- Support require_compatibilities, launch_type for Fargate
- Support network_configuration for awsvpc network mode
- Enable to delete unnecessary service by ecs_deploy
=> Support new features

lib/ecs_deploy/auto_scaler.rb
Modify to forcibly deregister the instance unless the essential task is running on the instance.
In case of running monitoring tasks (eg `dd-agent`) on the instance, `auto_scaler` can not downscale that instance.
It may be a good idea to provide this logic as an option on config because it will be a big logic change.
=> Modify instance deregister logic

lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb
This PR will reduce unnecessary TerminateInstances requests.
The following steps are performed after a TerminateInstances request, so the current implementation executes TerminateInstances requests over and over between step 2 and step 3.
1. Their instance state become "shutting-down"
2. They are deregistered from a ECS cluster
3. They are deregistered from a spot fleet requests
=> Terminate only running instances in spot fleet requests

lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb, lib/ecs_deploy/auto_scaler/service_config.rb, spec/ecs_deploy/auto_scaler/auto_scaling_group_config_spec.rb
This PR resolves https://github.com/reproio/ecs_deploy/issues/47.
=> Keep the balance of instance count per availability zone

CHANGELOG.md, lib/ecs_deploy/version.rb
* Add changelog since the initial release.
* Bump version.
I've added changelogs except internal changes.
=> Prepare release v1.0.0

CHANGELOG.md, lib/ecs_deploy/version.rb
=> Prepare release v1.0.1

lib/ecs_deploy/capistrano.rb, lib/ecs_deploy/service.rb
capacity_provider_strategy を 認識してservice作成時に反映できる様にする。
=> Add capacity_provider_strategy options to Service

lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb, spec/ecs_deploy/auto_scaler/auto_scaling_group_config_spec.rb
This PR resolves https://github.com/reproio/ecs_deploy/issues/84.
For the reason why this PR resolves the issue, see the description of the issue.
=> Fix Aws::AutoScaling::Errors::ValidationError

README.md, lib/ecs_deploy/auto_scaler.rb, lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb, lib/ecs_deploy/auto_scaler/cluster_resource_manager.rb, lib/ecs_deploy/auto_scaler/instance_drainer.rb, lib/ecs_deploy/auto_scaler/service_config.rb, lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb, lib/ecs_deploy/capistrano.rb, lib/ecs_deploy/instance_fluctuation_manager.rb, lib/ecs_deploy/scheduled_task.rb, lib/ecs_deploy/service.rb, lib/ecs_deploy/task_definition.rb, spec/ecs_deploy/instance_fluctuation_manager_spec.rb
Some quick fixes to the grammar of logs and a bit of the readme structure - I've got some thoughts on further improvements if you're interested, but for now have just stuck with the obvious fixes 🙂
=> fix: minor grammar improvements

spec/ecs_deploy/auto_scaler/instance_drainer_spec.rb
See https://github.com/aws/aws-sdk-ruby/pull/2918
=> Set random id to SQS stub message to pass CI

CHANGELOG.md, lib/ecs_deploy/version.rb
=> Prepare release 1.0.6

CHANGELOG.md, lib/ecs_deploy/version.rb
=> prepare release v1.0.7
