reproio/ecs_deploy

lib/ecs_deploy/task_definition.rb

デプロイ時にタスクを実行した時(db:migrate等)、終了を待たずに先に進んでしまうと、サービスコンテナがmigrate前に起動してARのカラム状態が更新されない可能性があるため、ワンタイムタスクの終了を待ち受けられるようにしました。

Add task waiter

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/task_definition.rb

serviceで利用するtask_definitionをrollbackするタスクを追加します。
前の修正と合わせて利用することで、特定のコンポーネントだけのロールバックも可能です。
何段階ロールバックするかは`STEP`環境変数で指定します。

Add ecs:rollback task

---

lib/ecs_deploy/service.rb

:desired_count is reqired for all services to create, but it was not specified for services without ELB.
@joker1007 plz review.

Fix missing desired_count for backend services

---

README.md

[scheduled_min_task_count](https://github.com/reproio/ecs_deploy/pull/7) の設定に関する記載が README になかったので追加します。

Update README for scheduled_min_task_count

---

lib/ecs_deploy/service.rb

Once you call deleteService API, its status become `INACTIVE` instead of being deleted. Inactive service cannot be updated but service which has the exactly same name can be newly created.
- http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html
This PR adds check whether the specified services is ACTIVE or not. If the status is not ACTIVE or service does not exist, try to create new one. Otherwise, the service will be updated.

filter inactive services

---

ecs_deploy.gemspec
lib/ecs_deploy.rb
lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/scheduled_task.rb

Support Scheduled Task deployment and implements capistrano task.
example.
```ruby
set :ecs_scheduled_tasks, [
{
cluster: "repro-development",
rule_name: "scheduled-task-test",
schedule_expression: "cron(0/5 * * * ? *)",
task_definition_name: "scheduled-task-test-dev_staging",
role_arn: "arn:aws:iam::113190696079:role/ecsEventsRole",
}
]
```
```sh
cap dev_staging ecs:deploy_scheduled_task
```

Support ScheduledTask

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/task_definition.rb

after `:register_task_definition`, `set(:ecs_registered_tasks)`.
Usage:
```ruby
set :ecs_executions_before_deploy, -> do
repro_rake = fetch(:ecs_registered_tasks)["ap-northeast-1"]["repro-rake"]
[
{
cluster: "repro-development",
region: "ap-northeast-1",
task_definition: {
task_definition_name: "#{repro_rake.family}:#{repro_rake.revision}",
main_container_name: "repro-rake"
},
command: ["db:ridgepole:apply"],
}
]
end
```

Enable to use registerd task_definition info

---

lib/ecs_deploy/capistrano.rb

This PR resolves errors like below:
```
NameError: undefined local variable or method `region' for main:Object
Did you mean?  regions
/path/to/vendor/bundle/ruby/2.4.0/bundler/gems/ecs_deploy-842fdfc8f24d/lib/ecs_deploy/capistrano.rb:26:in `block (3 levels) in <top (required)>'
/path/to/vendor/bundle/ruby/2.4.0/bundler/gems/ecs_deploy-842fdfc8f24d/lib/ecs_deploy/capistrano.rb:25:in `each'
/path/to/vendor/bundle/ruby/2.4.0/bundler/gems/ecs_deploy-842fdfc8f24d/lib/ecs_deploy/capistrano.rb:25:in `block (2 levels) in <top (required)>'
/path/to/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/path/to/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/path/to/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute' …
```

Fix a local variable name

---

README.md
lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/scheduled_task.rb

CloudWatch Events allow us to override container definitions by specifying `input` parameter and I want to use the feature.
cf. http://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html

Support container overrides in scheduled tasks

---

lib/ecs_deploy/capistrano.rb

if `ecs_scheduled_tasks` is no set, then deploy failed.
```
...
** Invoke after_release:add_ecs_scheduled_tasks (first_time)
** Execute after_release:add_ecs_scheduled_tasks
** Execute ecs:deploy_scheduled_task
cap aborted!
NoMethodError: undefined method `each' for nil:NilClass
/Users/kei_q/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/ecs_deploy-bf5d8e33ab90/lib/ecs_deploy/capistrano.rb:51:in `block (3 levels) in <top (required)>'
/Users/kei_q/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/ecs_deploy-bf5d8e33ab90/lib/ecs_deploy/capistrano.rb:50:in `each'
/Users/kei_q/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/ecs_deploy-bf5d8e33ab90/lib/ecs_deploy/capistrano.rb:50:in `block (2 levels) in <top (required)>' …
```

Fix deploy error when has no scheduled tasks

---

lib/ecs_deploy/auto_scaler.rb

`clear_client` was removed in e1f8d67.

Remove unused method calls

---

README.md
lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/configuration.rb
lib/ecs_deploy/service.rb

I want to adjust `wait_until` parameters.
`wait_until` has `delay` and `max_attempts` parameters.
Parameter defaults on `service_stable` waiter is `delay = 15` and `max_attempts = 40`
see also: http://docs.aws.amazon.com/sdkforruby/api/Aws/ECS/Client.html#wait_until-instance_method

Adjust `wait_until` timeout of ECS service_stable

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/scheduled_task.rb
lib/ecs_deploy/service.rb
lib/ecs_deploy/task_definition.rb

I want to use the default region of my profile
when I specify AWS_PROFILE environment variable.
Seahorse::Client::Configuration#apply_defaults assigns
default values only to options which are not specified.
* [aws-sdk-core/lib/aws-sdk-core/plugins/regional_endpoint.rb#L11-L27](https://github.com/aws/aws-sdk-ruby/blob/7d55a0d26e55531fd360486f9126f7dda1506d5a/gems/aws-sdk-core/lib/aws-sdk-core/plugins/regional_endpoint.rb#L11-L27)
* [aws-sdk-core/lib/seahorse/client/configuration.rb#L171-L178](https://github.com/aws/aws-sdk-ruby/blob/7d55a0d26e55531fd360486f9126f7dda1506d5a/gems/aws-sdk-core/lib/seahorse/client/configuration.rb#L171-L178)

Use Aws::Plugins::RegionalEndpoint.resolve_region

---

ecs_deploy.gemspec
lib/ecs_deploy.rb
lib/ecs_deploy/auto_scaler.rb
lib/ecs_deploy/scheduled_task.rb

AWS recommends library maintainers use service specific gems.
cf. https://aws.amazon.com/blogs/developer/upgrading-from-version-2-to-version-3-of-the-aws-sdk-for-ruby-2/
Currently all service specific gems will be installed
if there are no gems which depend on aws-sdk V2 in Gemfile.
I think this is not expected behavior.

Stop supporting aws-sdk V2

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/service.rb

Add `scheduling_strategy` option support for [Daemon Scheduling](https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-ecs-adds-daemon-scheduling/).
```ruby
set :ecs_services, [
{
name: "hello",
...
scheduling_strategy: "DAEMON"
}
]
```
@joker1007 Would you please review?

Support scheduling_strategy option

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/task_definition.rb

Fargate launch type needs to use `execution_roke_arn` parameter.
@joker1007 please review

Support execution_roke_arn on task_definition

---

lib/ecs_deploy/auto_scaler.rb

Modify instance deregister logic to reduce ECS API calls.

reduce ecs api call in running_essential_task? method

---

README.md
lib/ecs_deploy/auto_scaler.rb

We'll receive an error message like below if we try to detach more than 20 instances at a time:
> Aws::AutoScaling::Errors::ValidationError: List exceeds the maximum number of instances to detach. Please retry your request with fewer instances.
cf. https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/AutoScaling/Client.html#detach_instances-instance_method

Detach at most 20 instances at a time

---

lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb

Otherwise `list_container_instances` in `calculate_active_instance_capacity`
always lists instances in "default" cluster.

bugfix: Specify `cluster` in calculate_active_instance_capacity

---

lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb

In our usage, we receive Timeout::Error a few times a day for the reason like below:
1. The current target capacity is 20 and there are 5 instances which has 4 vCPU
2. The new target capacity is 18 but no instances will be terminated,
because the capacity will be 16 if one instance are terminated

Consider Timeout::Error in wait_for_capacity_decrease as a warning

---

lib/ecs_deploy/configuration.rb
lib/ecs_deploy/service.rb

Current Amazon ECS prefers to use service-linked role.
https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/using-service-linked-roles.html
Because of it, I remove implicit role parameter from API call.
Unless role parameter is given, ECS uses service-linked role automatically.
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-role

Remove default ecs_service_role in order to use service-linked role

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/service.rb
lib/ecs_deploy/task_definition.rb

This PR supports [tagging ECS resources](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html).
We can tag task definitions and services like below:
```ruby
set :ecs_tasks, [
{
name: "sleep",
container_definitions: [{
image: "ubuntu",
cpu: 256,
memory: 100,
essential: true,
name: "sleep",
command: ["sleep", "3600"],
}],
tags: [{ key: 'Image', value: 'ubuntu' }],
},
]
set :ecs_services, [
{
name: "sleep",
desired_count: 1,
deployment_configuration: {maximum_percent: 100, minimum_healthy_percent: 0},
tags: [
{ key: 'ServiceName', value: 'sleep' },
],
enable_ecs_managed_tags: true,
propagate_tags: 'SERVICE',
}
]
```

Support tagging ECS resources

---

lib/ecs_deploy/service.rb

`Aws::ECS::Errors::InvalidParameterException: Long arn format must be used for tagging operations` occurs when we try to update ECS services whose ARN is in old format.
This PR resolves it.

Resolve InvalidParameterException caused by old ARN formats

---

ecs_deploy.gemspec

This PR resolves the following error:
```
Bundler could not find compatible versions for gem "bundler":
In Gemfile:
bundler (~> 1.11)
Current Bundler version:
bundler (2.0.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (~> 1.11)' in any of the relevant sources:
the local ruby installation
```

Allow the use of  Bundler 2

---

README.md
lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb
lib/ecs_deploy/auto_scaler/service_config.rb
spec/ecs_deploy/auto_scaler/service_config_spec.rb

`Aws::ECS::Client#wait_until(:services_stable, ...)` waits until the running count of
the service become the value of `desired_count`.
cf. https://github.com/aws/aws-sdk-ruby/blob/1d6754a6a13aaf87cf7f1f66f211a9ee69301733/gems/aws-sdk-ecs/lib/aws-sdk-ecs/waiters.rb#L91-L96
The running count doesn't include the count of stopping tasks, so ecs_auto_scaler
can terminate instances where some stopping tasks are running.
This PR resolves the issue.

Wait until stopping tasks stops

---

README.md
lib/ecs_deploy/auto_scaler/cluster_resource_manager.rb

This PR fixes an error like below:
```
E, [2019-09-25T00:31:42.704520 #14230] ERROR -- : undefined local variable or method `e' for #<EcsDeploy::AutoScaler::ClusterResourceManager:0x00007f9cdca609c0> (NameError)
/Users/arabiki/ghq/src/github.com/reproio/ecs_deploy/lib/ecs_deploy/auto_scaler/cluster_resource_manager.rb:101:in `rescue in trigger_capacity_update'
/Users/arabiki/ghq/src/github.com/reproio/ecs_deploy/lib/ecs_deploy/auto_scaler/cluster_resource_manager.rb:98:in `trigger_capacity_update'
/Users/arabiki/ghq/src/github.com/reproio/ecs_deploy/lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb:40:in `update_desired_capacity'
/Users/arabiki/ghq/src/github.com/reproio/ecs_deploy/lib/ecs_deploy/auto_scaler.rb:64:in `block in main_loop' …
```

Fix "undefined local variable or method `e'"

---

lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb
lib/ecs_deploy/auto_scaler/cluster_resource_manager.rb
lib/ecs_deploy/auto_scaler/instance_drainer.rb
lib/ecs_deploy/auto_scaler/service_config.rb
lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb
spec/ecs_deploy/auto_scaler/instance_drainer_spec.rb

It takes about two minutes for auto scaling groups to launch new instances after we receive interruption warnings of their instances, so this PR will improve the stability of auto scaling groups managed by ecs_auto_scaler.
This PR will also resolve errors like "Aws::AutoScaling::Errors::ValidationError The instance
i-xxxxxxxxxxxxxxxxx is not in InService or Standby." in `detach_and_terminate_orphan_instances`.
These errors seem to occur in the following steps:
1. Spot instances are interrupted
2. The instances are deregistered from their ECS cluster due to termination
3. AutoScalingGroupConfig calls `detach_and_terminate_orphan_instances`
4. The instances are detached from their auto scaling group due to termination
5. AutoScalingGroupConfig tries to detach instances in …

Detach interrupted instances from ASG to launch other instances

---

lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb
spec/ecs_deploy/auto_scaler/auto_scaling_group_config_spec.rb

This commit fixes the following error.
```
detach_instances(auto_scaling_group_name:"xxxx",instance_ids:["i-000","i-111"],should_decrement_desired_capacity:true) Aws::AutoScaling::Errors::ValidationError The instance i-000 is not part of Auto Scaling group xxxx.
```
This error can happen in the following scenario.
1. InstanceDrainer drains and detaches interrupted spot instances
2. These instances are detached from an ASG almost immediately
3. ECS auto scaler starts scaling down an ECS cluster before they are deregistered from an ECS cluster
4. AutoScalingGroupConfig tries to detach them
5. `The instance i-xxxxx is not part of Auto Scaling group xxxx` error happens
because these instances are already detached form an ASG in step 2
In this commit, AutoScalingGroupConfig tries to detach …

Detach only auto scaling group instances

---

lib/ecs_deploy/configuration.rb
lib/ecs_deploy/service.rb

This change is useful when we investigate why some services take more time for their deployment than other services.
In addition, this change will also resolve https://github.com/reproio/ecs_deploy/issues/60 because `Aws::ECS::Client#wait_until` is no longer used.

Display only unstable services in EcsDeploy::Service#wait_all_running

---

README.md
lib/ecs_deploy/auto_scaler/service_config.rb
lib/ecs_deploy/auto_scaler/trigger_config.rb
spec/ecs_deploy/auto_scaler/service_config_spec.rb

Increasing the desired count of some services is sometimes meaningless.
For example, we shouldn't increase the desired count of a service inserting records into a database in the background if the database is heavily loaded.
This new option is useful in such cases.

Add prioritized_over_upscale_triggers option to triggers

---

lib/ecs_deploy/instance_fluctuation_manager.rb

In the previous version,
1. Update old tasks' state to "STOPPED" at the end of `ecs:deploy` task
2. In `EcsDeploy::InstanceFluctuationManager#decrease`, container instances that are in `DRAINING` status does not have any running tasks.
3. `wait_until(:tasks_stopped)` do nothing
4. Terminate EC2 instance while draining tasks
5. Tasks that take a long time to stop may be killed when terminating EC2 instance
In this version,
1. Update old tasks' state to "STOPPED" at the end of `ecs:deploy` task
2. Wait until tasks stopped properly after update container instance status to `DRAINING`
3. Terminate EC2 instances that have no running tasks
I've tested as followings:
Create resources using terraform using following main.tf:
```tf
provider "aws" {
region = "ap-northeast-1"
}
resource …
```

Wait until stop old tasks

---

lib/ecs_deploy/capistrano.rb

because ruby-3.0.0 cannot accept this style.

Fix passing keyword args

---

lib/ecs_deploy/task_definition.rb

This PR achieves to avoid raising Aws::ECS::Errors::ThrottlingException (https://github.com/reproio/ecs_deploy/pull/63) by AWS SDK feature.
I've tested manually.

retry register_task_definition by AWS SDK feature

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/service.rb

This PR add option `enable_execute_command` to support ECS Exec.
c.f. https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#create_service-instance_method

add option `enable_execute_command` to support ECS Exec

---

lib/ecs_deploy/instance_fluctuation_manager.rb
spec/ecs_deploy/instance_fluctuation_manager_spec.rb

ecs_deploy sometimes tries to detach instances that are terminated already because the status of ECS instances seems to remain 'DEREGISTERING' for a few minutes after they are terminated.
`Aws::AutoScaling::Errors::ValidationError` error may occur in the following case.
```
Aws::AutoScaling::Errors::ValidationError: The instance i-xxxxxxxx is not part of Auto Scaling group ecs-xxxx.
```
1. `increase`
2. `decrease`
- terminate redundant instances
3. `increase`
4. `decrease`
- ecs_deploy tries to detach instances whose status is 'DEREGISTERING' but which are terminated at step 2.

Terminate instances whose status is not 'DEREGISTERING'

---

lib/ecs_deploy/service.rb

capacity provider strategy ではない既存のサービスから capacity provider strategy へ移行する場合は force new deployment を実施する。

use force a new deployment, when switching from launch type to capacity provider strategy on an existing service

---

README.md
lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb
lib/ecs_deploy/auto_scaler/instance_drainer.rb
lib/ecs_deploy/auto_scaler/spot_fleet_request_config.rb
spec/ecs_deploy/auto_scaler/instance_drainer_spec.rb

If we set ECS_ENABLE_SPOT_INSTANCE_DRAINING to true, both ecs-agent and autoscaler try to drain instances. As a result, instances don't seem to be drained on rare occasions. Disabling the draining feature with the new option "disable_drainig" resolves the issue.

Make draining feature opt-outable

---

lib/ecs_deploy/auto_scaler/service_config.rb

The warning message helps us to know we should increase the max task count.

Display warning that desired count has reached max value

---

.github/workflows/test.yml
.travis.yml
ecs_deploy.gemspec
lib/ecs_deploy/auto_scaler/cluster_resource_manager.rb

Because Ruby 2.4 is no longer maintained and we want to use a syntax it doesn't support.
cf. https://endoflife.date/ruby

Stop supporting ruby 2.4

---

lib/ecs_deploy/service.rb

Same as the title.
Sample logs are below:
Deploy 6 tasks in a service.
```console
❯ bundle exec cap production ecs:deploy
I, [2022-12-19T11:19:33.014312 #2660955]  INFO -- : register task definition [okkez-sandbox-app] [ap-northeast-1] [OK]
I, [2022-12-19T11:19:33.430797 #2660955]  INFO -- : update service [okkez-sandbox-app] [okkez-sandbox-cluster-2] [ap-northeast-1] [OK]
I, [2022-12-19T11:19:33.433077 #2660955]  INFO -- : wait service stable [okkez-sandbox-app] [okkez-sandbox-cluster-2]
I, [2022-12-19T11:19:48.479488 #2660955]  INFO -- : wait service stable [okkez-sandbox-app] [okkez-sandbox-cluster-2]
I, [2022-12-19T11:20:03.578139 #2660955]  INFO -- : wait service stable [okkez-sandbox-app] [okkez-sandbox-cluster-2]
I, [2022-12-19T11:20:03.807488 #2660955]  INFO -- : (service …
```

Show service event logs while waiting for services

---

lib/ecs_deploy/service.rb

The ecs_deploy supports `propagateTags` options when creating ECS Service, but doesn't support it when updating ECS Service. The UpdateService API supports `propagateTags`, so ecs_deploy supports too.
c.f. https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html

Merge `propagate_tags` to service_options when updating service

---

README.md
lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/configuration.rb
lib/ecs_deploy/instance_fluctuation_manager.rb
lib/ecs_deploy/scheduled_task.rb
lib/ecs_deploy/service.rb
lib/ecs_deploy/task_definition.rb

Set `retry_mode` for ECS Client for capistrano by default. And, add variable `ecs_client_retry_params` to override parameter of #initialize
- c.f.
- https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html
- https://docs.aws.amazon.com/ja_jp/sdk-for-ruby/v3/api/Aws/ECS/Client.html#initialize-instance_method

enable retry_mode for ecs client

---

lib/ecs_deploy/capistrano.rb

I'm pretty sure right now this amounts to the same thing because of the way `c.default_region` is set (which means that `fetch(:ecs_region)` must be set, so the `if` here will never be true), but this should be consistent anyway so that if the logic for `c.default_region` does change it will properly matter for these tasks.

fix: make region fallback logic consistent in Capistrano tasks

---

lib/ecs_deploy/capistrano.rb
lib/ecs_deploy/task_definition.rb

Add `runtime_platform` keyword to the task definition.
It allows users to use Graviton2 on Fargate like the following;
```ruby
runtime_platform: { cpu_architecture: 'ARM64' },
````

Add runtime_platform to task_definition.

---

lib/ecs_deploy/service.rb

> The daemon scheduling strategy does not support placement
> strategies. Remove the placement strategy and try again
Maybe, aws-sdk-ecs 1.100.0 or later cannot deploy DAEMON service.

Delete option :placement_strategy if DAEMON service

---

lib/ecs_deploy/auto_scaler/auto_scaling_group_config.rb
spec/ecs_deploy/auto_scaler/auto_scaling_group_config_spec.rb

`InstanceDrainer` sometimes detaches instances that are not in `InService` or `Standby` for some reason.
I believe `AutoScalingGroupConfig#detach_instances` should only detach detachable instances because `InstanceDrainer` calls `detach_instances` directly when it receives instance interruption warnings.
ref. https://github.com/reproio/ecs_deploy/blob/1eae0bad1c16a17f9154904c4ca17259df3e62be/lib/ecs_deploy/auto_scaler/instance_drainer.rb#L107
Additionally, I exclude pending instances from detachable instances because EC2 instances sometimes stay in the `Pending` state for more than 10 minutes.
`EcsDeploy` detaches only detachable instances when it executes `update_desired_capacity`.
ref. https://github.com/reproio/ecs_deploy/blob/1eae0bad1c16a17f9154904c4ca17259df3e62be/lib/ecs_deploy/auto …

detach only detachable instances
